package asteris.app.view;

import asteris.app.AbstractView;
import asteris.dbi.DBI;
import asteris.util.Input;
import asteris.verifer.StringVerifer;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;

public class Login extends AbstractView {

    public Login() {
        super();
        initComponents();

        username.setInputVerifier(new StringVerifer());
        password.setInputVerifier(new StringVerifer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        DoLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOGIN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 16, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username.setText("cinta");
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 171;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 36, 0, 26);
        jPanel1.add(username, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 16, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        password.setText("pegawai");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 144;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 36, 0, 26);
        jPanel1.add(password, gridBagConstraints);

        DoLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DoLogin.setText("Login");
        DoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 121, 29, 26);
        jPanel1.add(DoLogin, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 29;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed

    }//GEN-LAST:event_usernameActionPerformed

    private void DoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoLoginActionPerformed
        String uname = username.getText();
        char[] pwd = password.getPassword();
        String pass = String.valueOf(pwd);
        boolean validasi = Input.Validate(uname, pass);
        if (!validasi) {
            dialog.Error("Login Gagal", "Username dan Password harus diisi.");
        } else {
            try {
                DBI data = new DBI("users");
                ResultSet que = data.RawSelect(
                        "SELECT * FROM `users` WHERE `username` = '" + uname + "' AND `password` = MD5('" + pass + "') LIMIT 1");
                while (que.next()) {
                    if (que.getString("username").equals(uname) && que.getString("password").equals(MD5(pass))) {
                        //todo : handle user type/role & save session
                        Login(
                                que.getString("username"),
                                que.getString("name"),
                                que.getString("id_user"),
                                que.getString("no_hp"),
                                que.getString("alamat"),
                                que.getString("email"),
                                que.getString("jabatan")
                        );

                        if (que.getString("jabatan").equals("Pegawai")) {
                            
                        }
                        if (que.getString("jabatan").equals("Admin")) {
                            
                        }

                        return;
                    }
                }
                dialog.Error("Login Gagal", "Username dan Password salah.");
                Exit();
            } catch (SQLException ex) {
                dialog.Error("Login Gagal", "Gagal terhubung ke Database.\nError: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_DoLoginActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void processWindowEvent(WindowEvent e) {
        super.processWindowEvent(e);
    }

}
